# Generated by Django 3.2.8 on 2021-10-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
