# Generated by Django 3.2.8 on 2021-10-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
